S_IFSOCK is defined in both glibc/musl
Fixes

preload.c:1183:46: error: '__S_IFSOCK' undeclared (first use in this function); did you mean 'S_IFSOCK'?

Signed-off-by: Khem Raj <raj.khem@gmail.com>