cbuild: Fix fc28 RPM creation
The python-argparse is part of python standard library and doesn't need
to be installed separately.

The following error is solved by this patch:
 No match for argument: python-argparse
 Error: Unable to find a match

Signed-off-by: Leon Romanovsky <leonro@mellanox.com>