Fix compilation warnings when NDEBUG is set
When NDEBUG is set (-DCMAKE_BUILD_TYPE=Release) and CFLAGS is set to
-Werorr, we get some compilation errors as the following:

rdma-core/libibverbs/neigh.c:378:13: error: variable 'rc' set but not used [-Werror=unused-but-set-variable]
     ssize_t rc;

Signed-off-by: Alaa Hleihel <alaa@mellanox.com>
Reviewed-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>
Signed-off-by: Leon Romanovsky <leon@kernel.org>